{"trial_id": "00", "hyperparameters": {"space": [{"class_name": "Int", "config": {"name": "lstm_cells", "default": null, "conditions": [], "min_value": 32, "max_value": 64, "step": 8, "sampling": "linear"}}, {"class_name": "Float", "config": {"name": "learning_rate", "default": 0.0015, "conditions": [], "min_value": 0.0015, "max_value": 0.004, "step": 0.0005, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "weight_decay", "default": 0.0015, "conditions": [], "values": [0.0015, 0.002, 0.0025, 0.003, 0.0035, 0.004], "ordered": true}}], "values": {"lstm_cells": 56, "learning_rate": 0.004, "weight_decay": 0.0015}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"c:\\Users\\Piotr\\.conda\\envs\\slr-env\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\Piotr\\.conda\\envs\\slr-env\\lib\\site-packages\\keras_tuner\\src\\engine\\base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"c:\\Users\\Piotr\\Python_projects\\Computer-Vision-Sign-Language\\jupyter_notebooks\\cv_keras_tuner.py\", line 40, in run_trial\n    x_train = tf.convert_to_tensor(x_train)\n  File \"c:\\Users\\Piotr\\.conda\\envs\\slr-env\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 153, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"c:\\Users\\Piotr\\.conda\\envs\\slr-env\\lib\\site-packages\\tensorflow\\python\\framework\\constant_op.py\", line 102, in convert_to_eager_tensor\n    return ops.EagerTensor(value, ctx.device_name, dtype)\ntensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run _EagerConst: Dst tensor is not initialized.\n"}